cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),

]

order/urls.py
from django.conf.urls import url
from order import views
from django.urls import path

app_name = 'order'
urlpatterns = [
    path('order_page/', views.OrderPage, name='order_page'),
    path('order/', views.createpost, name='createpost'),
    ]

shop/urls.py
from django.conf.urls import url
from django.urls import path, re_path

from . import views

app_name = 'shop'

urlpatterns = [
    url(r'^category/(?P<categoryid>\d+)/$', views.category_prodcut_list, name='product_list_by_category'),
    url(r'^product/(?P<productid>\d+)/$', views.product_detail, name='product_detail'),
    re_path('^$', views.category_prodcut_list, name='product_list'),
    #url(r'^(?P<categoryid>\d+)/$', views.product_list, name='product_list_by_category'),
    #url(r'^(?P<productid>\d+)/$', views.product_detail, name='product_detail'),
]

shoppingcart/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
]

cart/models.py
from django.db import models

# Create your models here.

order/models.py
from django.db import models

# Create your models here.
class buyerdata(models.Model):
    first_name = models.CharField(max_length=300, unique=False)
    last_name = models.CharField(max_length=300, unique=False)
    address = models.CharField(max_length=300, unique=False)

shop/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=150, db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=100, db_index=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id'),)

    def __str__(self):
        return self.name

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 26)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
    return render(request, 'detail.html', {'cart': cart})
#
# def cart_redirrect(request):
#     cart=Cart(request)
#     return render(request, 'order : order_page', {'cart' : cart})

order/views.py
from django.shortcuts import render
from django.views.decorators.http import require_POST

from cart.cart import Cart
from .models import buyerdata
def OrderPage(request):
    cart = Cart(request)
    return render(request,'order/orderr.html', {'cart' : cart})

@require_POST
def createpost(request):
    if request.method == 'POST':
        if request.POST.get('first_name') and request.POST.get('last_name') and request.POST.get('address'):
            post = buyerdata()
            post.first_name = request.POST.get('first_name')
            post.last_name = request.POST.get('last_name')
            post.address = request.POST.get('address')
            post.save()

            return render(request, 'order/response.html')
        else:
            return render(request, 'order/error.html')
    else:
        return render(request, 'order/orderr.html')

shop/views.py
from django.shortcuts import render
from .models import Category, Product
from cart.forms import CartAddProductForm

# Create your views here.
def product_list(request):
    products = Product.objects.all()
    categories = Category.objects.all()
    context = {
        'products': products,
        'categories': categories
    }
    return render(request, 'list.html', context)

def category_prodcut_list(request, categoryid = 1 ):
    categories = Category.objects.all()
    products = Product.objects.filter(category=categoryid)
    context = {
        'products': products,
        'categories': categories
    }
    return render(request, 'categoryproductlist.html', context)
def product_detail(request, productid):
    id = productid
    produs = Product.objects.get(pk=int(id))
    print(produs.id)
    cart_product_form = CartAddProductForm()
    context = {
        'produs': produs,
        'cart_product_form': cart_product_form,
    }
    return render(request, 'produs.html', context)

cart/templates/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
 {% with totail_items=cart|length %}
    {% if cart|length > 0 %}
        My Shopping Order:
        <a href="{% url "cart:cart_detail" %}" style="color: #ffffff">
            {{ totail_items }} item {{ totail_items|pluralize }}, Kshs. {{ cart.get_total_price }}
        </a>
        {% else %}
        Your cart is empty.
    {% endif %}
{% endwith %}
<br />
{% for item in cart %}
    {% with product=item.product  %}
        {{ product.name }}
        <form action="{% url "cart:cart_add" product.id %}" method="post">
                                    {% csrf_token %}
                                    {{ item.update_quantity_form.quantity }}
                                    {{ item.update_quantity_form.update }}
                                    <input type="submit" value="Update">
                                </form>
        <a href="{% url "cart:cart_remove" product.id %}">Remove</a>
 {{ item.price }}
 {{ item.total_price }}
 </br>
    {% endwith %}
 {% endfor %}
Pretul total este: {{ cart.get_total_price }}
<br><br><br><b>
<a href="{% url "order:order_page" %}"> ORDER </b>

</body>

</html>

order/templates/order/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
There was an error. Try again later!
</body>
</html>

order/templates/order/orderr.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<table border="black">
{% for item in cart %}
    <td>
    {% with product=item.product%}

        Product: {{product.name}} <br>
        Quantity: {{item.quantity}}<br>
        Price : {{product.price}}<br>
    </td>

{%endwith%}
{%endfor%}

{% for item in cart %}
    <td>
    {% with product=item.product%}

        Product: {{product.name}} <br>
        Quantity: {{item.quantity}}<br>
        Price : {{product.price}}<br>
    </td>

{%endwith%}
{%endfor%}

<form action="{% url 'order:createpost' %}" method="POST">
    {% csrf_token %}
    First name: <input type="text" name="first_name"/><br/>
    Last name: <input type="text" name="last_name"/><br/>
    Address: <input type="text" name="address"/><br/>
    <input type="submit" value="Send"/>
</form>



<form action="{% url 'order:createpost' %}" method="POST">
    {% csrf_token %}
    First name: <input type="text" name="first_name"/><br/>
    Last name: <input type="text" name="last_name"/><br/>
    Address: <input type="text" name="address"/><br/>
    <input type="submit" value="Send"/>
</form>


</table>
</body>
</html>

order/templates/order/response.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
Your delivery has been sent!
</body>
</html>

shop/templates/categoryproductlist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<table>
    <tr>
    <td width="300px" style="border: 0px">
        {% for category in categories %}
            <a href="http://localhost:8000/shop/category/{{category.id}}">{{ category.name }} <br /> </a>
        {% endfor %}
    </td>
    <td>
        {% for product in products %}
            <a href="http://localhost:8000/shop/product/{{product.id}}/">{{product.name}}</a> </br>
        {% endfor %}
    </td>
    </tr>
</table>

<br />
<br />

</body>
</html>

shop/templates/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<table>
    <tr>
    <td width="300px" style="border: 0px">
        {% for category in categories %}
            <a href="#">{{ category.name }} <br /> </a>
        {% endfor %}
    </td>
    <td>
        {% for product in products %}
            <a href="http://localhost:8000/shop/product/{{product.id}}/">{{product.name}}</a> </br>
        {% endfor %}
    </td>
    </tr>
</table>

<br />
<br />

</body>
</html>

shop/templates/produs.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
Produs name: {{produs.name}} <br />
Produs descriere: {{produs.description}} <br />
Pret: {{produs.price}} $ <br />
<form action="{% url "cart:cart_add" produs.id %}" method="post">
    {% csrf_token %}
    {{ cart_product_form }}
    <input type="submit" value="add to cart" class="btn btn-primary">


</form>

</body>
</html>